### ISSUE TITLE
전체 UI 개선 작업

### ISSUE THREAD

**Issue by Hajin-Bang** [Hajin-Bang/Project_BookMark#19]
## 📄 Description
전체 UI 개선 작업

## ✔️ Todo
- [x] 각 페이지 UI 개선
- [x] 메인 페이지 Card 반응형 
- [x] 상품 상세 페이지 
- [x] 인터랙티브 UI 요소 개발
- [x] 데이터 채우기
