### ISSUE TITLE
상품 재고 감소, 이미지 수정 오류 해결

### ISSUE THREAD

**Issue by Hajin-Bang** [Hajin-Bang/Project_BookMark#21]
## 📄 Description
상품 재고 감소, 이미지 수정 오류 해결

## ✔️ Todo
- [x] 상품 재고 감소 
- [ ] 이미지 수정
- [x] 스크롤 위치 문제 해결
- [x] 콘솔 에러 해결
