### ISSUE TITLE
전체 코드 개선, 불필요한 코드 삭제

### ISSUE THREAD

**Issue by Hajin-Bang** [Hajin-Bang/Project_BookMark#22]
## 📄 Description
전체 코드 개선, 불필요한 코드 삭제

## ✔️ Todo
- [x] 전체 코드 개선
- [x] 불필요한 코드 삭제 
- [x] api, types 파일 분리
