### ISSUE TITLE
회원가입 / 로그인 기능 구현

### ISSUE THREAD

**Issue by Hajin-Bang** [Hajin-Bang/Project_BookMark#3]
## 📄 Description
회원가입 / 로그인 기능 구현

## ✔️ Todo
- [x] Firebase Authentication 설정
- [x] 회원가입 기능 구현
- [x] 로그인 기능 구현
- [x] 라우팅 처리
