### ISSUE TITLE
렌더링 최적화 작업

### ISSUE THREAD

**Issue by Hajin-Bang** [Hajin-Bang/Project_BookMark#50]
## 📄 Description
렌더링 최적화 작업

## ✔️ Todo
- [ ] React.memo 적용 
- [ ] useMemo, useCallback 사용 
- [ ] React Profiler를 통한 성능 분석
